name: Dummy Workflow
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: self-hosted


    steps:
      - uses: actions/checkout@v4


      - name: Run a one-line script
        run: echo "Hello, world!"


      - name: azure login
        run: az login --service-principal --username 136e4513-6466-4756-9c03-21fbd9e7866d --password vra8Q~J0JmRSuZfPSMLM7W_I5ABrDwgI0-1xPcGs --tenant 4039544a-5fa0-4809-92a7-047ca14bcc69


      - name: init
        run: terraform init


      - name: plan
        run: terraform plan


   
